[package]
name = "demonhide"
version = "0.1.0"
edition = "2021"
rust-version = "1.90.0"

[dependencies]
glib = "0.17"
wayland-client = "0.31"
wayland-protocols = { version = "0.31", features = ["client", "unstable"] }
sysinfo = "0.37"
